{
 "title": "System Overview",
 "time": { "from": "now-60m", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 20, "x": 0, "y": 0 },
   "targets": [
    { "expr": "sum by(Zone) (ap_clients)", "legendFormat": "{{DeviceName}}" }
   ]
  },
  {
   "title": "Total Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ap_clients)", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Rx / Tx",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "sum(ap_rx)", "legendFormat": "Receive" },
    { "expr": "sum(ap_tx)", "legendFormat": "Transmit" }
   ]
  },
  {
   "title": "Tx / Rx",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 20, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "sum(ap_tx)", "legendFormat": "Transmit" },
    { "expr": "sum(ap_rx) * -1", "legendFormat": "Receive" }
   ]
  },
  {
   "title": "AP Alerts",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(DeviceName) (ap_alerts) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}