{
 "title": "Single AP",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "selected_ap", "label": "AP", "query": { "query": "label_values(ap_tx,DeviceName)" } }
  ]
 },
 "panels": [
  {
   "title": "Latency",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "sum by(MAC) (ap_latency_24g{DeviceName=\"$selected_ap\"})",
     "legendFormat": "2.4G"
    },
    {
     "expr": "sum by(MAC) (ap_latency_5g{DeviceName=\"$selected_ap\"})",
     "legendFormat": "5G"
    }
   ]
  },
  {
   "title": "Airtime",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(MAC) (ap_airtime_24g{DeviceName=\"$selected_ap\"})",
     "legendFormat": "2.4G"
    },
    {
     "expr": "sum by(MAC) (ap_airtime_5g{DeviceName=\"$selected_ap\"})",
     "legendFormat": "5G"
    }
   ]
  },
  {
   "title": "Airtime",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 20, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum by(MAC) (ap_airtime_24g{DeviceName=\"$selected_ap\"})",
     "legendFormat": "2.4G"
    },
    {
     "expr": "sum by(MAC) (ap_airtime_5g{DeviceName=\"$selected_ap\"})",
     "legendFormat": "5G"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "gauge",
   "gridPos": { "h": 10, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(MAC) (ap_latency_24g{DeviceName=\"$selected_ap\"})",
     "legendFormat": "2.4G"
    },
    {
     "expr": "sum by(MAC) (ap_latency_5g{DeviceName=\"$selected_ap\"})",
     "legendFormat": "5G"
    }
   ]
  },
  {
   "title": "Clients / Connection Failures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 10 },
   "targets": [
    {
     "expr": "sum by(MAC) (ap_clients{DeviceName=\"$selected_ap\"})",
     "legendFormat": "Clients"
    },
    {
     "expr": "sum by(MAC) (ap_failures{DeviceName=\"$selected_ap\"})",
     "legendFormat": "Failures"
    }
   ]
  },
  {
   "title": "RX / TX",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(MAC) (ap_tx{DeviceName=\"$selected_ap\"})",
     "legendFormat": "Transmit (TX)"
    },
    {
     "expr": "sum by(MAC) (ap_rx{DeviceName=\"$selected_ap\"}) * -1",
     "legendFormat": "Receive (RX)"
    }
   ]
  },
  {
   "title": "Status",
   "type": "state-timeline",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 19 },
   "targets": [
    {
     "expr": "sum by(Status) (ap_uptime{DeviceName=\"$selected_ap\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}