{
 "title": "Client",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "selected_client", "label": "Client", "query": { "query": "label_values(client_tx,Mac)" } }
  ]
 },
 "panels": [
  {
   "title": "APs",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(ApName) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Data Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum by(Mac) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "Transmit"
    },
    {
     "expr": "sum by(Mac) (client_rx{Mac=\"$selected_client\"}) * -1",
     "legendFormat": "Receive"
    }
   ]
  },
  {
   "title": "IPs",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "sum by(IP) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "SSIDs",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "sum by(SSID) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VLANs",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Vlan) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Type",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 2, "x": 2, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(OsType) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "OS Vendor",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 2, "x": 4, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(OsVendorType) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Hostname",
   "type": "piechart",
   "gridPos": { "h": 5, "w": 2, "x": 6, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(Hostname) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "View in other locations",
   "type": "text",
   "gridPos": { "h": 5, "w": 4, "x": 8, "y": 12 },
   "options": {
    "content": "<a href=\"https://ehps.rmmservice.com/#/search?searchValue=${selected_client}&searchFilter=all\" target=\"_blank\">Ninja</a><br>\r\n"
   }
  },
  {
   "title": "Zone",
   "type": "state-timeline",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "sum by(Zone) (client_tx{Mac=\"$selected_client\"})",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}