{
 "title": "Single Zone",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "selected_zone", "label": "Zone", "query": { "query": "label_values(ap_alerts,Zone)" } }
  ]
 },
 "panels": [
  {
   "title": "Connection Failtures",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 20, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum by(DeviceName) (ap_failures{Zone=\"$selected_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "stat",
   "gridPos": { "h": 9, "w": 4, "x": 20, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ap_clients{Zone=\"$selected_zone\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Airtime",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(DeviceName) (ap_airtime_5g{Zone=\"$selected_zone\"} > 10)",
     "legendFormat": "5G {{DeviceName}}"
    },
    {
     "expr": "sum by(DeviceName) (ap_airtime_24g{Zone=\"$selected_zone\"} > 20)",
     "legendFormat": "2.4G {{DeviceName}}"
    }
   ]
  },
  {
   "title": "RX/TX sum",
   "type": "stat",
   "gridPos": { "h": 12, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ap_rx{Zone=\"$selected_zone\"})",
     "legendFormat": "Receive (RX)"
    },
    {
     "expr": "sum(ap_tx{Zone=\"$selected_zone\"})",
     "legendFormat": "Transmit (TX)"
    }
   ]
  },
  {
   "title": "Clients",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 20, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "sum by(DeviceName) (ap_clients{Zone=\"$selected_zone\"})",
     "legendFormat": "{{DeviceName}}"
    }
   ]
  }
 ]
}