services:
  # Metrics collector
  prometheus:
    image: prom/prometheus:latest
    expose:
      - 9090
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
      # persist data
      # - prometheus_storage:/prometheus
    command: --web.enable-lifecycle --config.file=/etc/prometheus/prometheus.yml
    network_mode: host

  # log viewer
  grafana:
    network_mode: host
    image: grafana/grafana:latest
    volumes:
      - ./grafana:/etc/grafana/provisioning/
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_FEATURE_TOGGLES_ENABLE=traceqlEditor
    expose:
      - 3000
    depends_on:
      - prometheus

# volumes:
#   prometheus_storage:
#   grafana_storage:
