global:
  scrape_interval: 60s 
  query_log_file: /etc/prometheus/query.log

scrape_configs:
  - job_name: smartzone 
    static_configs:
      # put a list of all the nodes you are monitoring
      - targets: ['localhost:8000']
    metric_relabel_configs:
      - source_labels: [Zone]
        action: drop
        regex: 'Default Zone'
      - source_labels: [Zone]
        action: drop
        regex: 'R550'

  - job_name: sz_clients
    scrape_interval: 10m
    metrics_path: /clients
    static_configs:
      - targets: ['localhost:8000']

  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
