use serde::Deserialize;
use crate::smartzone::*;

#[derive(Deserialize)]
#[allow(dead_code)]
pub struct AP {
    #[serde(rename = "deviceName")]
    pub device_name: String,
    #[serde(rename = "description")]
    pub description: String,
    #[serde(rename = "status")]
    pub status: String,
    #[serde(rename = "alerts")]
    pub alerts: u64,
    #[serde(rename = "ip")]
    pub ip: String,
    #[serde(rename = "ipv6Address")]
    pub ipv6_address: String,
    #[serde(rename = "txRx")]
    pub tx_rx: u64,
    #[serde(rename = "noise24G")]
    pub noise_24g: i64,
    #[serde(rename = "noise5G")]
    pub noise_5g: i64,
    #[serde(rename = "noise6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub noise_6g: i64,
    #[serde(rename = "airtime24G")]
    pub airtime_24g: u64,
    #[serde(rename = "airtime5G")]
    pub airtime_5g: u64,
    #[serde(rename = "airtime6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub airtime_6g: u64,
    #[serde(rename = "latency24G")]
    pub latency24g: u64,
    #[serde(rename = "latency50G")]
    pub latency50_g: u64,
    #[serde(rename = "latency6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub latency6_g: u64,
    #[serde(rename = "capacity")]
    pub capacity: u64,
    #[serde(rename = "capacity24G")]
    pub capacity24_g: u64,
    #[serde(rename = "capacity50G")]
    pub capacity50_g: u64,
    #[serde(rename = "capacity6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub capacity6_g: u64,
    #[serde(rename = "connectionFailure")]
    pub connection_failures: f64,
    #[serde(rename = "model")]
    pub model: String,
    #[serde(rename = "apMac")]
    pub ap_mac: String,
    #[serde(rename = "channel24G")]
    pub channel_24g: String,
    #[serde(rename = "channel5G")]
    pub channel_5g: String,
    #[serde(rename = "channel6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub channel_6g: String,
    #[serde(rename = "channel24gValue")]
    pub channel_24g_value: i64,
    #[serde(rename = "channel50gValue")]
    pub channel50g_value: u64,
    #[serde(rename = "channel6gValue")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub channel6g_value: u64,
    #[serde(rename = "meshRole")]
    pub mesh_role: String,
    #[serde(rename = "meshMode")]
    pub mesh_mode: String,
    #[serde(rename = "zoneName")]
    pub zone_name: String,
    #[serde(rename = "zoneAffinityProfileName")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub zone_affinity_profile_name: String,
    #[serde(rename = "apGroupName")]
    pub ap_group_name: String,
    #[serde(rename = "extIp")]
    pub ext_ip: String,
    #[serde(rename = "extPort")]
    pub ext_port: String,
    #[serde(rename = "firmwareVersion")]
    pub firmware_version: String,
    #[serde(rename = "serial")]
    pub serial: String,
    #[serde(rename = "retry24G")]
    pub retry24_g: u64,
    #[serde(rename = "retry5G")]
    pub retry5_g: u64,
    #[serde(rename = "retry6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub retry6_g: u64,
    #[serde(rename = "configurationStatus")]
    pub configuration_status: String,
    #[serde(rename = "lastSeen")]
    pub last_seen: u64,
    #[serde(rename = "numClients")]
    pub num_clients: u64,
    #[serde(rename = "numClients24G")]
    pub num_clients_24g: u64,
    #[serde(rename = "numClients5G")]
    pub num_clients_5g: u64,
    #[serde(rename = "numClients6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub num_clients_6g: u64,
    #[serde(rename = "tx")]
    pub tx: u64,
    #[serde(rename = "tx24G")]
    pub tx_24g: u64,
    #[serde(rename = "tx50G")]
    pub tx_50g: u64,
    #[serde(rename = "tx6G")]
    pub tx_6g: u64,
    #[serde(rename = "rx")]
    pub rx: u64,
    #[serde(rename = "rx24G")]
    pub rx_24g: u64,
    #[serde(rename = "rx50G")]
    pub rx_50g: u64,
    #[serde(rename = "rx6G")]
    pub rx_6g: u64,
    #[serde(rename = "txRx24G")]
    pub tx_rx_24g: u64,
    #[serde(rename = "txRx50G")]
    pub tx_rx_50g: u64,
    #[serde(rename = "txRx6G")]
    pub tx_rx_6g: u64,
    #[serde(rename = "location")]
    pub location: String,
    #[serde(rename = "wlanGroup24Id")]
    pub wlan_group24_id: String,
    #[serde(rename = "wlanGroup50Id")]
    pub wlan_group50_id: String,
    #[serde(rename = "wlanGroup6gId")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub wlan_group6g_id: String,
    #[serde(rename = "wlanGroup24Name")]
    pub wlan_group24_name: String,
    #[serde(rename = "wlanGroup50Name")]
    pub wlan_group50_name: String,
    #[serde(rename = "wlanGroup6gName")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub wlan_group6g_name: String,
    #[serde(rename = "enabledBonjourGateway")]
    pub enabled_bonjour_gateway: bool,
    #[serde(rename = "controlBladeName")]
    pub control_blade_name: String,
    #[serde(rename = "lbsStatus")]
    pub lbs_status: String,
    #[serde(rename = "administrativeState")]
    pub administrative_state: String,
    #[serde(rename = "registrationState")]
    pub registration_state: String,
    #[serde(rename = "provisionMethod")]
    pub provision_method: String,
    #[serde(rename = "provisionStage")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub provision_stage: String,
    #[serde(rename = "registrationTime")]
    pub registration_time: u64,
    #[serde(rename = "managementVlan")]
    pub management_vlan: u64,
    #[serde(rename = "configOverride")]
    pub config_override: bool,
    #[serde(rename = "indoorMapId")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub indoor_map_id: String,
    #[serde(rename = "apGroupId")]
    pub ap_group_id: String,
    #[serde(rename = "indoorMapName")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub indoor_map_name: String,
    #[serde(rename = "indoorMapLocation")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub indoor_map_location: String,
    #[serde(rename = "deviceGps")]
    pub device_gps: String,
    #[serde(rename = "connectionStatus")]
    pub connection_status: String,
    #[serde(rename = "zoneId")]
    pub zone_id: String,
    #[serde(rename = "zoneFirmwareVersion")]
    pub zone_firmware_version: String,
    #[serde(rename = "domainId")]
    pub domain_id: String,
    #[serde(rename = "domainName")]
    pub domain_name: String,
    #[serde(rename = "partnerDomainId")]
    pub partner_domain_id: String,
    #[serde(rename = "dpIp")]
    pub dp_ip: String,
    #[serde(rename = "controlBladeId")]
    pub control_blade_id: String,
    #[serde(rename = "isCriticalAp")]
    pub is_critical_ap: bool,
    #[serde(rename = "crashDump")]
    pub crash_dump: u64,
    #[serde(rename = "cableModemSupported")]
    pub cable_modem_supported: bool,
    #[serde(rename = "cableModemResetSupported")]
    pub cable_modem_reset_supported: bool,
    // "swapInMac": null,
    #[serde(rename = "swapInMac")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub swap_in_mac: String,
    // "swapOutMac": null,
    #[serde(rename = "swapOutMac")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub swap_out_mac: String,
    #[serde(rename = "isOverallHealthStatusFlagged")]
    pub is_overall_health_status_flagged: bool,
    #[serde(rename = "isLatency24GFlagged")]
    pub is_latency_24g_flagged: bool,
    #[serde(rename = "isLatency50GFlagged")]
    pub is_latency_50g_flagged: bool,
    #[serde(rename = "isLatency6GFlagged")]
    pub is_latency6_gflagged: bool,
    #[serde(rename = "isCapacity24GFlagged")]
    pub is_capacity24_gflagged: bool,
    #[serde(rename = "isCapacity50GFlagged")]
    pub is_capacity50_gflagged: bool,
    #[serde(rename = "isCapacity6GFlagged")]
    pub is_capacity6_gflagged: bool,
    #[serde(rename = "isConnectionFailure24GFlagged")]
    pub is_connection_failure24_gflagged: bool,
    #[serde(rename = "isConnectionFailure50GFlagged")]
    pub is_connection_failure50_gflagged: bool,
    #[serde(rename = "isConnectionFailure6GFlagged")]
    pub is_connection_failure6_gflagged: bool,
    #[serde(rename = "isConnectionTotalCountFlagged")]
    pub is_connection_total_count_flagged: bool,
    #[serde(rename = "isConnectionFailureFlagged")]
    pub is_connection_failure_flagged: bool,
    #[serde(rename = "isAirtimeUtilization24GFlagged")]
    pub is_airtime_utilization24_gflagged: bool,
    #[serde(rename = "isAirtimeUtilization50GFlagged")]
    pub is_airtime_utilization50_gflagged: bool,
    #[serde(rename = "isAirtimeUtilization6GFlagged")]
    pub is_airtime_utilization6_gflagged: bool,
    #[serde(rename = "uptime")]
    pub uptime: u64,
    #[serde(rename = "eirp24G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub eirp24_g: u64,
    #[serde(rename = "eirp50G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub eirp50_g: u64,
    #[serde(rename = "eirp6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub eirp6_g: u64,
    #[serde(rename = "supportFips")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub support_fips: String,
    #[serde(rename = "ipsecSessionTime")]
    pub ipsec_session_time: u64,
    #[serde(rename = "ipsecTxPkts")]
    pub ipsec_tx_pkts: u64,
    #[serde(rename = "ipsecRxPkts")]
    pub ipsec_rx_pkts: u64,
    #[serde(rename = "ipsecTxBytes")]
    pub ipsec_tx_bytes: u64,
    #[serde(rename = "ipsecRxBytes")]
    pub ipsec_rx_bytes: u64,
    #[serde(rename = "ipsecTxDropPkts")]
    pub ipsec_tx_drop_pkts: u64,
    #[serde(rename = "ipsecRxDropPkts")]
    pub ipsec_rx_drop_pkts: u64,
    #[serde(rename = "ipsecTxIdleTime")]
    pub ipsec_tx_idle_time: u64,
    #[serde(rename = "ipsecRxIdleTime")]
    pub ipsec_rx_idle_time: u64,
    #[serde(rename = "ipType")]
    pub ip_type: String,
    #[serde(rename = "ipv6Type")]
    pub ipv6_type: String,
    #[serde(rename = "packetCaptureState")]
    pub packet_capture_state: String,
    #[serde(rename = "cellularWanInterface")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_wan_interface: String,
    #[serde(rename = "cellularConnectionStatus")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_connection_status: String,
    #[serde(rename = "cellularSignalStrength")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_signal_strength: String,
    #[serde(rename = "cellularIMSISIM0")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_imsisim0: String,
    #[serde(rename = "cellularIMSISIM1")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_imsisim1: String,
    #[serde(rename = "cellularICCIDSIM0")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_iccidsim0: String,
    #[serde(rename = "cellularICCIDSIM1")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_iccidsim1: String,
    #[serde(rename = "cellularIsSIM0Present")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_is_sim0_present: String,
    #[serde(rename = "cellularIsSIM1Present")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_is_sim1_present: String,
    #[serde(rename = "cellularTxBytesSIM0")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_tx_bytes_sim0: String,
    #[serde(rename = "cellularTxBytesSIM1")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_tx_bytes_sim1: String,
    #[serde(rename = "cellularRxBytesSIM0")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_rx_bytes_sim0: String,
    #[serde(rename = "cellularRxBytesSIM1")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_rx_bytes_sim1: String,
    #[serde(rename = "cellularActiveSim")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_active_sim: String,
    #[serde(rename = "cellularIPaddress")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_ipaddress: String,
    #[serde(rename = "cellularSubnetMask")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_subnet_mask: String,
    #[serde(rename = "cellularDefaultGateway")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_default_gateway: String,
    #[serde(rename = "cellularOperator")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_operator: String,
    #[serde(rename = "cellular3G4GChannel")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular3_g4_gchannel: String,
    #[serde(rename = "cellularCountry")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_country: String,
    #[serde(rename = "cellularRadioUptime")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_radio_uptime: String,
    #[serde(rename = "cellularGpsHistory")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cellular_gps_history: String,
    #[serde(rename = "fipsEnabled")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub fips_enabled: String,
    #[serde(rename = "medianTxRadioMCSRate24G")]
    pub median_tx_radio_mcsrate24_g: u64,
    #[serde(rename = "medianTxRadioMCSRate50G")]
    pub median_tx_radio_mcsrate50_g: u64,
    #[serde(rename = "medianTxRadioMCSRate6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub median_tx_radio_mcsrate6_g: u64,
    #[serde(rename = "medianRxRadioMCSRate24G")]
    pub median_rx_radio_mcsrate24_g: u64,
    #[serde(rename = "medianRxRadioMCSRate50G")]
    pub median_rx_radio_mcsrate50_g: u64,
    #[serde(rename = "medianRxRadioMCSRate6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub median_rx_radio_mcsrate6_g: u64,
    #[serde(rename = "monitoringEnabled")]
    pub monitoring_enabled: bool,
    #[serde(rename = "txPowerOffset24G")]
    pub tx_power_offset24_g: u64,
    #[serde(rename = "txPowerOffset5G")]
    pub tx_power_offset5_g: u64,
    #[serde(rename = "txPowerOffset6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub tx_power_offset6_g: u64,
    #[serde(rename = "rxDesense24G")]
    pub rx_desense24_g: u64,
    #[serde(rename = "rxDesense5G")]
    pub rx_desense5_g: u64,
    #[serde(rename = "rxDesense6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub rx_desense6_g: u64,
    #[serde(rename = "poePortStatus")]
    pub poe_port_status: String,
    #[serde(rename = "cumulativeTx24G")]
    pub cumulative_tx24_g: u64,
    #[serde(rename = "cumulativeTx5G")]
    pub cumulative_tx5_g: u64,
    #[serde(rename = "cumulativeTx6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cumulative_tx6_g: u64,
    #[serde(rename = "cumulativeRx24G")]
    pub cumulative_rx24_g: u64,
    #[serde(rename = "cumulativeRx5G")]
    pub cumulative_rx5_g: u64,
    #[serde(rename = "cumulativeRx6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cumulative_rx6_g: u64,
    #[serde(rename = "cumulativeTxRx24G")]
    pub cumulative_tx_rx24_g: u64,
    #[serde(rename = "cumulativeTxRx5G")]
    pub cumulative_tx_rx5_g: u64,
    #[serde(rename = "cumulativeTxRx6G")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub cumulative_tx_rx6_g: u64,
    #[serde(rename = "isDual5gMode")]
    pub is_dual5g_mode: bool,
    #[serde(rename = "indoorMapXy")]
    #[serde(deserialize_with = "deserialize_null_default")]
    pub indoor_map_xy: MapXY,
}

#[derive(Deserialize, Default)]
pub struct MapXY {
    pub x: f32,
    pub y: f32,
}

// #[serde(deserialize_with="nullable_u64")]
